-- No longer required: PondEntity now maps the `name` property to the
-- existing `pond_name` column via @Column({ name: 'pond_name' }), so
-- TypeORM's synchronize no longer attempts to add a new `name` column.
-- The `pond_name` column already exists and is NOT NULL in schema.sql.
--
-- Historical context (previously needed when the entity used an unmapped
-- `name` column without a default):
-- UPDATE ponds
-- SET name = COALESCE(NULLIF(trim(location), ''), 'Unnamed pond')
-- WHERE name IS NULL OR trim(name) = '';
--
-- ALTER TABLE ponds
--   ALTER COLUMN name SET NOT NULL;
